INSERT INTO message (NAME, DESCRIPTION) VALUES ('Milos' , 'ESADASDSAA');
INSERT INTO message (NAME, DESCRIPTION) VALUES ('eMA' , 'ESADASDSAA');
INSERT INTO message (NAME, DESCRIPTION) VALUES ('uROS' , 'ESADASDSAA');
INSERT INTO message (NAME, DESCRIPTION) VALUES ('NEMANJA' , 'ESADASDSAA');
